import type { Metadata } from "next";
import StyledComponentsRegistry from "../../lib/registry";
import { ReactQueryClientProvider } from "../../providers/ReactQueryClientProvider";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryClientProvider>
      <html lang="pt-br">
        <body>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}